### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AbstractModule'

### ISSUE THREAD

**Issue by tomoat** [deepmind/learning-to-learn#15]
```python
Matplotlib required for plot()
Traceback (most recent call last):
  File "evaluate.py", line 26, in <module>
    import meta
  File "/Users/tomato/Sites/learning-to-learn/meta.py", line 32, in <module>
    import networks
  File "/Users/tomato/Sites/learning-to-learn/networks.py", line 31, in <module>
    import preprocess
  File "/Users/tomato/Sites/learning-to-learn/preprocess.py", line 26, in <module>
    class Clamp(snt.AbstractModule):
AttributeError: 'module' object has no attribute 'AbstractModule'
```
```sh
$ python -V
Python 2.7.13
$ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by sergomezcol** [comment]
Sorry, I can't reproduce this. I've just reinstalled both TensorFlow and Sonnet and everything works as expected. Are you running this from a folder that contains a 'sonnet' subfolder by any chance? That's a common source of this type of problem I think.

**Comment by tomoat** [comment]
```sh
⬢  learning-to-learn  master ✗ gl
Already up-to-date.
⬢  learning-to-learn  master ✗ vim README.md
⬢  learning-to-learn  master ✗ python train.py --problem=mnist --save_path=./mnist
Matplotlib required for plot()
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    import meta
  File "/Users/tomato/Sites/learning-to-learn/meta.py", line 32, in <module>
    import networks
  File "/Users/tomato/Sites/learning-to-learn/networks.py", line 31, in <module>
    import preprocess
  File "/Users/tomato/Sites/learning-to-learn/preprocess.py", line 26, in <module>
    class Clamp(snt.AbstractModule):
AttributeError: 'module' object has no attribute 'AbstractModule'
⬢  learning-to-learn  master ✗ ls
CONTRIBUTING  convergence_test.py  meta.pyc      networks.py       preprocess.py       problems.py       util.py
LICENSE       evaluate.py          meta_test.py  networks.pyc      preprocess.pyc      problems_test.py
README.md     meta.py              mnist/        networks_test.py  preprocess_test.py  train.py
⬢  learning-to-learn  master ✗ gss
?? meta.pyc
?? networks.pyc
?? preprocess.pyc
⬢  learning-to-learn  master ✗ python -V
Python 2.7.13
⬢  learning-to-learn  master ✗ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by vignywang** [comment]
you may lack  dill 

`pip install dill`

**Comment by tomoat** [comment]
@vignywang 
```sh
⬢  learning-to-learn  master ✗ pip install dill
Requirement already satisfied: dill in /usr/local/lib/python2.7/site-packages
```

**Comment by DavidWalz** [comment]
Did you by chance install "sonnet" from pip? https://pypi.python.org/pypi/sonnet/0.1.6

**Comment by act65** [comment]
Ok. I have the same issue. 
```
python train.py --problem=mnist --save_path=/tmp/mnist_opt
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    import meta
  File "/Volumes/ExtraDiskSpace/Documents/learning-to-learn/meta.py", line 
32, in <module>
    import networks
  File "/Volumes/ExtraDiskSpace/Documents/learning-to-learn/networks.py", $
ine 31, in <module>
    import preprocess
  File "/Volumes/ExtraDiskSpace/Documents/learning-to-learn/preprocess.py"$
 line 26, in <module>
    class Clamp(snt.AbstractModule):
AttributeError: 'module' object has no attribute 'AbstractModule'
```

Working on OSX (10.11.6) in a venv. python (2.7.10). 
And yea, installed sonnet (0.1.6) via pip.

Also, the original issue mentions matplotlib. Not sure if it's related, but I had to manually set the backend for matplotlib to be happy. https://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv

**Comment by davidsketchdeck** [comment]
Here's how I fixed the problem for my environment:

`pip uninstall sonnet`
`pip install dm-sonnet`

**Comment by KnowBetterHelps** [comment]
I also have this problem, and I tried a lot of ways, still cannot work, did you solved this?

Matplotlib required for plot()
Traceback (most recent call last):
  File "/home/huyuezhi/tts-train/deng/train-tts-voicenet/voicenet-master/src/run_tts.py", line 30, in <module>
    from models.tf_model import TfModel
  File "/home/huyuezhi/tts-train/deng/train-tts-voicenet/voicenet-master/src/models/tf_model.py", line 27, in <module>
    class TfModel(snt.AbstractModule):
AttributeError: 'module' object has no attribute 'AbstractModule'

**Comment by jhyoocoder** [comment]
I also got the same error, but thanks to davidsketchdeck@, it works!
